### ISSUE TITLE
Issue with copyright symbols

### ISSUE THREAD

**Issue by johnjjung** [mervick/aes-everywhere#13]
This is python3.5

I'm sure I have `# -*- coding: utf-8 -*-` at the top of the file, but not sure what's going on.

```
if __name__ == '__main__':    #code to execute if called from command-line
    test = '''©'''
    print(aes256().decrypt(aes256().encrypt(test, "pass"), "pass"))
```

`self.__pkcs5_padding(raw)` outputs
```
raw_padded b'\xc2\xa9\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x0f\x0f'
```

Then throws an error at 

```
cipher_encrypted = cipher.encrypt(raw_padded)
```
```
  File "/usr/local/lib/python3.5/site-packages/Crypto/Cipher/blockalgo.py", line 244, in encrypt
    return self._cipher.encrypt(plaintext)
ValueError: Input strings must be a multiple of 16 in length

```

**Comment by johnjjung** [comment]
Well it looks like if we do something like this, then it'll strip out unsafe characters

```
if __name__ == '__main__':    #code to execute if called from command-line
    test = '''©'''
    test = test.encode('ascii','ignore').decode('utf-8')
    print(aes256().decrypt(aes256().encrypt(test, "pass"), "pass"))
```

**Comment by johnjjung** [comment]
Issues with passing `None`

```
if __name__ == '__main__':    #code to execute if called from command-line
    test = None
    print(aes256().decrypt(aes256().encrypt(test, "pass"), "pass"))
```

Throws error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/base64.py", line 81, in b64decode
    s = _bytes_from_decode_data(s)
  File "/usr/local/lib/python3.5/base64.py", line 46, in _bytes_from_decode_data
    "string, not %r" % s.__class__.__name__) from None
TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```

**Comment by johnjjung** [comment]
Same thing with emojis

```
if __name__ == '__main__':    #code to execute if called from command-line
    test = '''🌷'''
    test = test.encode('ascii','ignore').decode('utf-8')
    print(aes256().decrypt(aes256().encrypt(test, "pass"), "pass"))
```

Just doubled checked and emoji's can be encrypted decrypted using aes256cbc

![Screen Shot 2019-04-15 at 8 27 22 PM](https://user-images.githubusercontent.com/2654677/56173754-03e04d80-5fbd-11e9-8201-1e97f16986fd.png)
